### ISSUE TITLE
Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by alexcroox** [epicshaggy/capacitor-native-biometric#11]
Just added `capacitor-native-biometric@2.1.1-cap3.0` to my working projects and now builds are failing with this error:

![image](https://user-images.githubusercontent.com/1065835/117778802-eb8f9b00-b235-11eb-9143-3067edc343da.png)

```
/Users/alex/Projects/silo/node_modules/capacitor-native-biometric/ios/Plugin/Plugin.swift:2:8: Compiling for iOS 11.0, but module 'Capacitor' has a minimum deployment target of iOS 12.0: /Users/alex/Library/Developer/Xcode/DerivedData/App-gfkzyhtgfjiewlbkcionrnbtvhdf/Build/Products/Debug-iphonesimulator/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

I'm not using the plugin JS bridge yet, I've just installed and cap synced so far.

**Comment by alexcroox** [comment]
https://github.com/epicshaggy/capacitor-native-biometric/blob/a9256bdd9260333911aea5c8e2614a793302aac9/CapacitorNativeBiometric.podspec#L11

Issue here maybe?

**Comment by alexcroox** [comment]
Thanks! My builds are automated with fastlane on a CI so I’ll wait for a new release :)

**Comment by buleglay** [comment]
@epicshaggy could you please have a look at this PR that alexcroox raised, it's blocking the build due to the mismatch iOS deployment target. Many thanks!
