### ISSUE TITLE
isAvailable is false, but BiometryType is 3, instead of 0 - Android Pixel 4a API 30

### ISSUE THREAD

**Issue by lehnavid** [epicshaggy/capacitor-native-biometric#14]
Hey,

I've expected the `biometricType` to be 0 when the `isAvailable` returns false.

What exactly is `isAvailable` expressing then?

**Comment by epicshaggy** [comment]
If I'm not mistaken it means isAvailable returns true if the device is enrolled in biometrics at the system level, biometricType will return the available biometric method and it doesn't care if it is enrolled.  Can you confirm if your device is or not enrolled?  If not I can look into it.

**Comment by lehnavid** [comment]
Hey Mate, thanks for the fast reply.

You're indeed right. I haven't had enrolled biometrics on the emulator.
It works perfectly now!
