### ISSUE TITLE
capacitor/core incorrectly set to "latest" on 2.1.0

### ISSUE THREAD

**Issue by andrecadete** [epicshaggy/capacitor-native-biometric#15]
Hi,

In your `package.json` you have the dependency `"@capacitor/core": "latest"`. This is incorrectly applied in the `2.1.0` NPM release, instead of only in the `2.1.1-cap3.0`, since the current `latest` is 3+ on capacitor/core.

This leads to multiple problems being the first one Type issues when compiling.

I would open a PR but since you're using Master for both releases I'm not sure how you want to go about it.

The correct version for `2.1.0` should be `"@capacitor/core": "2.4.*"`.

Thanks in advance

**Comment by andrecadete** [comment]
I can add that this creates backwards incompatibility to any previous version. We are forced to upgrade to capacitor v3 which is not something we can do right now.

**Comment by epicshaggy** [comment]
That was my mistake, I'm new relatively new to node and git.

**Comment by andrecadete** [comment]
It's all good mate :) This is a common mistake in many libraries, people tend to forget "latest" is really latest major which is often backwards incompatible. I actually said fuck it and upgraded our whole app to Capacitor v3 in about 1hour and it seems to be working fine.

If I may suggest you could make 2.x.x releases only for capacitor v2 and 3.x.x to capacitor v3. Let me know if you need help @epicshaggy !

**Comment by epicshaggy** [comment]
I went ahead and updated it for capacitor 3.  From now on I'll make seperate branches for new major versions. Thanks @andrecadete

**Comment by andrecadete** [comment]
By the way @epicshaggy you can also just make releases in github and point your NPM versions to that specific release. Releases just reference a specific commit so you don't have to manage several branches. Of course for this particular use-case, if you wanted to have v2 and v3 and keep patching both, a different branch would be the best option. But for instance if you wanted to have v2 deprecated but still working with no further patches, you could simply have a commit compatible with v2, make a release for that and then commit again for v3 and make a release for that. From there onwards you wouldn't need to worry about breaking the v2 release!

**Comment by epicshaggy** [comment]
Thanks @andrecadete this works great for me!
