### ISSUE TITLE
Sometimes Face ID not detected in iPhone 11 Pro Max and showing Popup with Try again 

### ISSUE THREAD

**Issue by Ishanka94** [epicshaggy/capacitor-native-biometric#2]
Device is updated to iOS 14. Normally when face id not detected, passcode should prompts. But popup shows with Try again and  there is no option to control those using plugin. Is there any other way to handle this scenario and hope this plugin supports latest iOS version. Thanks

**Comment by epicshaggy** [comment]
Hi, sorry for the late reply.  I implemented this without passcode in mind, but I'd be happy to implement it.
