### ISSUE TITLE
iOS - setCredentials does not set the new username/password on the existing server key

### ISSUE THREAD

**Issue by jkprem31** [epicshaggy/capacitor-native-biometric#27]
iOS
Set username/password using server key, then try to save another username/password using the same server key.
Now if you call getCredentials, you would get the previous username/password.

Android
Works as expected

**Comment by saschamander** [comment]
Any updates on this? I have the same issue.

**Comment by saschamander** [comment]
Found a workaround. If you first delete the existing credentials, you can set them as intended. 

```js
await NativeBiometric.deleteCredentials({server: "..."})
await NativeBiometric.setCredentials({
  username: email,
  password: password,
  server: "...",
})
```

**Comment by Incrust2024** [comment]
Does the NativeBiometric.setCredentials() method stores the credentials in encrypted format or as it is as passed i.e. in plain text
