### ISSUE TITLE
android.permission.USE_BIOMETRIC  not getting set

### ISSUE THREAD

**Issue by choffmeyer** [epicshaggy/capacitor-native-biometric#33]
Android USE_BIOMETRIC Not getting set on device or asking user.  In settings you can see after the install the use_biometric is missing therefore tells me it was never pickedup.

when checking for availability it's false but show shows type as 4 / face

Cap 3.2.5
Android v11, v10

 <uses-permission android:name="android.permission.USE_BIOMETRIC" />

**Comment by NicholasWhitallNSWHP** [comment]
I too found this on a Pixel 5. Through some debugging I found that adding to android manifest (despite its deprecation)

<uses-permission android:name="android.permission.USE_FINGERPRINT" />

That I could get it to prompt.
