### ISSUE TITLE
biometryType is Shown only as 3 .

### ISSUE THREAD

**Issue by lugan1** [epicshaggy/capacitor-native-biometric#42]
![image](https://user-images.githubusercontent.com/39528583/146884801-fdcbe00e-f7a2-4c64-93ae-595911d348ec.png)
![image](https://user-images.githubusercontent.com/39528583/146884853-a8c61b61-c100-4bf2-9697-747f0c925ba1.png)

Phone : galaxy S9
biometrics support : face auth, fingerprint,  eye auth

**registered biometrics : face auth**

use : ionic capacitor (Angular)

**biometry Type only shown 3**

**Comment by Lexa950609** [comment]
Hi @lugan1 did you find a workaround for that? I'm facing the same issue

**Comment by zvitek** [comment]
Yes, because `BiometryType` is `Enum`. 
Your response code means, you have `FINDEGERPRINT` available.

```js
export declare enum BiometryType {
    NONE = 0,
    TOUCH_ID = 1,
    FACE_ID = 2,
    FINGERPRINT = 3,
    FACE_AUTHENTICATION = 4,
    IRIS_AUTHENTICATION = 5
}
```

**Comment by mfrey-WELL** [comment]
For android the plugin only returns one available type. The order is defined here: https://github.com/epicshaggy/capacitor-native-biometric/blob/c3062a83eaa2ef0041ae3e9fcfa43a23ae716f40/android/src/main/java/com/epicshaggy/biometric/NativeBiometric.java#L78
