### ISSUE TITLE
How to know if user declines permission

### ISSUE THREAD

**Issue by valdo99** [epicshaggy/capacitor-native-biometric#44]
Hi,

Everything working well, though when a user declines  biometric access, will popup the device passcode, how can we know if a user declindes the biometric permissioin?
so we can handle this information and do not ask the user again for it!

Also if user declines and we try to verify the user with Biometrics it will always ask for the user passcode.

any advice will be helpful.

**Comment by jonah-butler** [comment]
#10 
I believe it is talked about in this PR.
There is error code messaging you can access if you are interested in handling the failed prompt differently.
