### ISSUE TITLE
How to close biometic validation on error from verifyIdentity()?

### ISSUE THREAD

**Issue by nesha14586** [epicshaggy/capacitor-native-biometric#45]
Hi,

We are using this plugin in our client's Ionic/Capacitor 3 app to trigger biometric validation. Everything is working fine. I have one question tho.
Our client wants to switch to app internal pincode after unsuccessful biometric scan. Currently we see native option to unlock with phone's passcode. 
Is there a way either to disable this button or when scan returns an error, to just close the scan alltogether as scan is triggered on app pincode page so client would automatically be able to enter app pin?

![image](https://user-images.githubusercontent.com/16090791/161561996-1b711943-bf7b-458b-879b-86bd6ff01332.png)

**Comment by epicshaggy** [comment]
Hello,
As far as I know you cannot avoid the system's default passcode option. I change the policy being used from `.deviceOwnerAuthentication` to `.deviceOwnerAuthenticationWithBiometrics`, however, [apple's documentation](https://developer.apple.com/documentation/localauthentication/lapolicy/deviceownerauthenticationwithbiometrics) says the following:

> Policy evaluation fails if Touch ID or Face ID is unavailable or not enrolled. Evaluation also fails after three failed Touch ID attempts. After two failed Face ID attempts, the system offers a fallback option, but stops trying to authenticate with Face ID. Both Touch ID and Face ID authentication are disabled system-wide after five consecutive unsuccessful attempts, even when the attempts span multiple evaluation calls. When this happens, the system requires the user to enter the device passcode to reenable biometry.

**Comment by nesha14586** [comment]
Hi @epicshaggy ,

Thanks for replying! 
My assumption was the same, that you cannot avoid the system's default passcode option.
However, do you have an example of closing the system authentication opposite to starting it with .verifyIdentity()?
