### ISSUE TITLE
Build failing on iOS in XCode 13.2.1. with Swift 5

### ISSUE THREAD

**Issue by chrisweight** [epicshaggy/capacitor-native-biometric#46]
in Plugin.swift -> `verifyIdentity()`, XCode throws an error: 
![image](https://user-images.githubusercontent.com/468638/161998004-615af0b5-b546-4bb9-a334-f969c32624c7.png)

removing the `defaultValue` label fixes the build:

![image](https://user-images.githubusercontent.com/468638/161998199-f6a3f355-45e8-4b27-aeb9-96f321d480f4.png)

**Comment by danyyacoub** [comment]
Thanks @chrisweight , I made a pull request and a temporary fork https://github.com/danyyacoub/capacitor-native-biometric until it's fixed here.

**Comment by BogdanOstrovskiy** [comment]
Hello! Could you please merge this MR as soon as possible. We need this fix. Thanks for fast error handling!

**Comment by signorbusi** [comment]
I can confirm this works perfectly, please merge 🙏

**Comment by antonio-masotti** [comment]
Hello, we're having the same problem. Thanks in advance for merging! ;)

**Comment by sisdevsoftware** [comment]
Hi all. Will there be any update on this soon?
I did update the plugin to 3.1.0 and still got the issue

**Comment by antonio-masotti** [comment]
A PR was created ( #47 ) but there is a discussion there. It's still not merged.

**Comment by squio** [comment]
Hi @epicshaggy I just created the a simple [PR](https://github.com/epicshaggy/capacitor-native-biometric/pull/52) which only removes the label from the default value; hope you're able to merge this soon and create a new bugfix release!

**Comment by chrisweight** [comment]
Ok, so there are now 3 PR's that address this issue - @epicshaggy - is this likely to be resolved soon at all? Looks like a there's a fair amount of dependency on this plugin from people. If maintenance is an issue - is it worth turning this over to `@capacitor-community` for the longer term?

Cheers for all your work on this!
