### ISSUE TITLE
On Android biometric type returns as  Fingerprint

### ISSUE THREAD

**Issue by vneethareddy** [epicshaggy/capacitor-native-biometric#5]
I am testing Biometrics using this plugin. My device is supporting  face authentication but always it returns fingerprint. I enrolled with face still it returns fingerprint .
private int getAvailableFeature() {
        if (getContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_FINGERPRINT)) {
            return FINGERPRINT;
        } else if (getContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_FACE)) {
            return FACE_AUTHENTICATION;
        } else if (getContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_IRIS)) {
            return IRIS_AUTHENTICATION;

        } else {
            return NONE;
        }
    }

the above method executes and my device supports fingerprint and face.Even though i enrolled with face it will give result as fingerprint only.

Expected Behaviour::: 

the getAvailableFeature feature should returns which biometric the device is enrolled..

**Comment by web-felicons** [comment]
Hi, this is happening to me to. It's a problem as we'll go live with the app soon.

Will this be fixed?

**Comment by epicshaggy** [comment]
I'll go over the documentation to see if I missed something.  I can't thoroughly test it since I don't own Android devices.

**Comment by web-felicons** [comment]
> I'll go over the documentation to see if I missed something. I can't thoroughly test it since I don't own Android devices.

Thank you!

**Comment by epicshaggy** [comment]
I haven't found a way to check which biometric is enrolled.  The `isAvailable()` just checks if the system has the feature and returns on the first one.

**Comment by jonthia** [comment]
The current API does not provide a way for us to determine which type of biometrics the user has set as their preferred method. The recommendation is to simply use generics labels i.e. 'Login with biometrics' rather than 'Login with fingerprint'.
