### ISSUE TITLE
Integration to Capacitor v3

### ISSUE THREAD

**Issue by oneclickwebstudio** [epicshaggy/capacitor-native-biometric#6]
Hello. Are you going to integrate plugin to Capacitor v3?

importing `Plugins` is deprecated in third version of Capacitor

**Comment by epicshaggy** [comment]
Hello @oneclickwebstudio,

Yes, I plan on doing so, but I have to update a project and a community plugin first.

**Comment by mburger81** [comment]
Shouldn't this plugin be part of the official community plugins?

**Comment by oneclickwebstudio** [comment]
> Shouldn't this plugin be part of the official community plugins?

Yes! Exactly! Don't know why Capacitor didn't add Biometrics

**Comment by KirstenStake** [comment]
@epicshaggy hello, just a friendly reminder for upgrade plans for this plugin :) (https://capacitorjs.com/docs/v3/updating/plugins/3-0)
