### ISSUE TITLE
AppTheme not found error on build

### ISSUE THREAD

**Issue by odbryan** [epicshaggy/capacitor-native-biometric#63]
After upgrading to Capacitor 4, when building an APK via AppFlow the build is failing with the following error:

ERROR:AAPT: error: resource style/AppTheme (aka com.epicshaggy.biometric.capacitornativebiometric:style/AppTheme) not found.

The APK will build fine within Android Studio, even though Android Studio is reporting Cannot Resolve Symbol 'AppTheme' for line 4 of styles.xml within the plugin.

Adding a parent attribute to that line resolves the Android Studio complaint, but I am not familiar enough with native Android to understand if that's the best/most correct fix, and if it will also resolve the build error.

**Comment by autodisk-kjelt** [comment]
Same error here

**Comment by jraschella** [comment]
Running into the same issue.

**Comment by autodisk-kjelt** [comment]
Also

**Comment by epicshaggy** [comment]
This style was meant to extend the base AppTheme of the app, but I'm not sure if I'm doing it correctly. Regardless I removed the style because it wasn't being used.

**Comment by odbryan** [comment]
Thank you!  That resolved my issue.
