### ISSUE TITLE
can i use this library for angular pwa

### ISSUE THREAD

**Issue by amirheydari9** [epicshaggy/capacitor-native-biometric#68]
can i use this library for angular pwa

**Comment by rocco** [comment]
No, this Plugin relies on iOS/Android native code. Also see https://github.com/epicshaggy/capacitor-native-biometric/blob/master/src/web.ts (you get ""Method not implemented." errors) in the PWA version of your Capacitor/Angular Project.

**Comment by amirheydari9** [comment]
thank you
do you know a package that is suitable for this issue ?
or do you know a source to introduce ?

‫‪Pilito‬‏ ***@***.***‬‏> در تاریخ سه‌شنبه ۱۱ اکتبر ۲۰۲۲
ساعت ۱۶:۲۳ نوشت:‬
