### ISSUE TITLE
Error: Method not implemented. isAvailable()

### ISSUE THREAD

**Issue by oneclickwebstudio** [epicshaggy/capacitor-native-biometric#7]
NativeBiometric not implements exported functions. 
I'm using the latest version of capacitor-native-biometric; 
Running on iPhone 12 mini.

Here is my code:
```
import` {NativeBiometric, AvailableResult} from 'capacitor-native-biometric';

export class PinComponent implements OnInit {
    constructor(
    ) {
      NativeBiometric.isAvailable().then((res: AvailableResult) => console.log(res)})
    }
}
```

`console.log(NativeBiometric)` returns:

```
[Log] NativeBiometricWeb {config: {name: "NativeBiometric", platforms: ["web"]}, loaded: false, listeners: {}, windowListeners: {}, addWindowListener: function, …} (vendor.js, line 16937)
```

The same stuff on android...

What could be the problem?

**Comment by oneclickwebstudio** [comment]
Works with `"@capacitor/core": "^3.0.0-beta.1",`
with `"@capacitor/core": "^3.0.0-beta.2",` it won't work.

**Comment by oneclickwebstudio** [comment]
Please, any fixes?

**Comment by epicshaggy** [comment]
Hi, I'll look into this, could be just an conflict with capacitor 3.  I'll let you know if I find anything. @oneclickwebstudio

**Comment by oneclickwebstudio** [comment]
> Hi, I'll look into this, could be just an conflict with capacitor 3. I'll let you know if I find anything. @oneclickwebstudio

Capacitor 3 includes many cool improvements. Unfortunately now it's in beta.

**Comment by geoff-schultz** [comment]
I am encountering this on capacitor v2.4.2

**Comment by epicshaggy** [comment]
Hi, sorry it took so long, I took this week to upgrade all my plugins to capacitor 3, check it out now

**Comment by oneclickwebstudio** [comment]
Closing this issue. `isAvailable() ` works with latest version of plugin.
