### ISSUE TITLE
iOS 14.4 support?

### ISSUE THREAD

**Issue by andrecadete** [epicshaggy/capacitor-native-biometric#8]
Hi,

Sorry for the lack of details but I implemented this almost exactly like the example you provide and it works fine on Android (both touch id and face id) and on iOS up to version 13.x. However we have another device on iOS 14.4 and in there `isAvailable()` returns false. The same device uses Touch Id with other (native) apps so it seems to be specific for this plugin.

Do I need to be aware of special considerations for iOS 14.4?

**Comment by andrecadete** [comment]
Jesus nevermind, closing this. The guy that had tested this on his iOS 14.4 device forgot the fact he didn't have any face or touch id configured on his system (was a brand new instalation) 😂. Thankfully I remembered to ask. Sorry for the false alarm and for wasting your time!

**Comment by epicshaggy** [comment]
Hahaha, no worries! @andrecadete
