### ISSUE TITLE
Set Credential Error

### ISSUE THREAD

**Issue by sagun-gautam** [epicshaggy/capacitor-native-biometric#87]
I am receiving error on setCredentials method when using following data, it was working before not anymore.

**NativeBiometric.setCredentials**

```
callbackId: "92098633"
methodName: "setCredentials"
options: {username: "1001", password: "abc1234#", server: "com.sagun.appName"}
pluginId: "NativeBiometric"
type: "message"
```

**Error Response**
```
{
  errorMessage: "The operation couldn’t be completed. (CapacitorNativeBiometric.NativeBiometric.KeychainError error 0.)"
  message: "The operation couldn’t be completed. (CapacitorNativeBiometric.NativeBiometric.KeychainError error 0.)"
}
```

**Comment by BenRacicot** [comment]
Seeing this error as well but this is the first time using this project for FaceID.
@sagun-gautam  Where you able to get passed this?

**Comment by mobilityvalley** [comment]
Seeing the same error too, can't find a solution +1

**Comment by SergioZhydecky** [comment]
I have the same

**Comment by mcelikdev** [comment]
Try to remove the credentials first with NativeBiometric.deleteCredentials({ ... }) and then set the credentials
